export const ERROR_MESSAGES = {
  SERVER_ERROR: "INTERNAL SERVER ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  SERVER_RUN_FAILURE: "COULD NOT START SERVER",
};

export const SUCCESS_MESSAGES = {
  HEALTH_CHECK_SUCCESS: "HEALTH CHECK SUCCESSFULL",
  CONNECTED: "CONNECTED TO POSTGRES",
  SERVER_RUN_SUCCESS: "SERVER STARTED ON PORT",
};
